// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require("Witnet")
const WitnetBridgeInterface = artifacts.require("WitnetBridgeInterface")
const PetroToken = artifacts.require("PetroToken")
const PetroTokenICO = artifacts.require("PetroTokenICO")
const PriceFeed = artifacts.require("PriceFeed")
module.exports = function (deployer) {
  deployer.link(Witnet, [PetroToken, PetroTokenICO, PriceFeed])
  deployer.deploy(PetroToken, PriceFeed.address, 20000000)
  deployer.deploy(PetroTokenICO, PetroToken.address, 1000000000000000)
  deployer.deploy(PriceFeed, WitnetBridgeInterface.address)
}
